import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import Footer from "./components/Footer";
import SessionProvider from "./components/SessionProvider";
import "./globals.css";
import NavMenu from "./components/NavMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "App Asafe nextjs",
  description: "Generated by Pmn",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()


  return (
    <html lang="en">
      <body className={`${inter.className} font-montserrat`}>
        <SessionProvider session={session}>
          <main className="min-h-screen w-full pb-24">
            <NavMenu />
            <span>
              {children}
            </span>
            <Footer />
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
